### PR TITLE
Check the size of the NevisTPC Header + ADC words and see if they fit in the fragment.  Truncate ADC words if fragment is too short to protect against segfaults

### PR DESCRIPTION
**Pull request by tomjunk**
### Description

This PR adds a check on the size of the data in the artdaq fragment that is used by NevisTPCFragment,  comparing it with the size of the NevisTPCHeader and the ADC words (each of which is assumed to be two bytes per word -- a future commit (already committed, that's commit number 2)  will change this to sizeof(NevisTPC_ADC_t)).  If the total size of the data is bigger than the size of the fragment, then the number of ADC words is reduced so as not to run past the end of the fragment when looping over ADC words.

Subtractions are checked not to return negative values, in case of use of unsigned integers.

### Related Repository Branches

No other repository branches are needed.

### Testing details

SBND Run 17722, taken Nov. 17, 2024, shows problems with the decoder utilities in sbndaq_artdaq_core v1_10_3.  In fifty events in one file, valgrind reports four Invalid reads of size 2 in NevisTPCUtilities.cc, and this happens when the expected size exceeds the fragment size.  Memory corruption has knock-on effects.  Gray Putnam noted a segfault in a reco job far downstream of the actual invalid memory access.

Run 17722 reconstructs fine with the fix above, and valigrind returns no Invalid read errors.

I also tested this on a file in run 12007, taken in March 2024, with an older version of the data format.  The NevisTPC fragment metadata got an extra word in new data.  Reading in old data succeeded in decoding, though the initial memory reservation is too small (64 is put in for the number of samples but it's really the channel count).

### CODE REVIEW

**Comment by tomjunk** [comment]
The third commit  checks for channel headers or trailers while decoding channel 63 and stops the loop over the input words if it sees that.  There's an assumption that channel 63 is always the last channel in the list.

The reason for this check is that in run 17806, event 60804, when decoding the fragment from crate 3 FEM 10, a little bit of extra data appears off the end of the last channel's waveform.  A new channel header for channel 2 appears in the data stream with one ADC word.  It overwrites a fully-decoded channel 2's waveform, leaving a hole in the data.  Jose and Nupur tell me sometimes some extra data get overwritten on the end of a waveform, and we read out extra samples just to make sure we have enough.  It seems as if the extra data sometimes contains things that can be interpreted as channel headers.

The symptom was:

Begin processing the 11th record. run: 17806 subRun: 1 event: 60804 at 27-Nov-2024 12:09:10 CST
11-27 12:09:10.440160   NevisTPCUtilities:72  WARNING decode_data: Previously found channel 2. Overwriting old data!

and one raw waveform, for offline channel 8656, was found to have length 1.  This commit prevents the previously decoded waveform for that channel on that event from being overwritten with the extra data on the end of the fragment.

**Comment by tomjunk** [comment]
I found a cleaner, more general solution to the problem of extra stuff on the end -- if a channel has already been found and a header comes along saying there's another waveform for that channel, skip decoding the second and subsequent waveforms for that channel.  That way, if the extra stuff is in the middle of the fragment, or if the channels aren't read out in order for some reason, we still solve the problem.  The assumption here is that the first time we see a waveform for a channel, it is the good one.

**Comment by gennadiy-fnal** [comment]
@eyandel @afilkins @tomjunk  should I merge this branch into the upcoming release?

**Comment by tomjunk** [comment]
I am all in favor!  But then again, it's my PR.  It fixes a segfault Gray ran into.

**Review by gputnam — APPROVED** [review]
Looks good! So that I understand -- are duplicate channels still appearing? Or does this PR also remove that problem.

**Comment by tomjunk** [comment]
@gputnam The duplicate channels are coming in the data from the FEM.  They aren't really new waveforms for the same data, they are just overwritten data at the end of the fragment, some of which gets interpreted as the start word of a channel that's already been decoded.  So when those arrive, the decoder prints out a TRACE message saying it is not going to replace the first waveform but drop any subsequent appearances of that channel.  In the run you sent, that's the behavior observed in the new code.  Neither the old code nor the new code puts duplicates in the output decoded stream, it's just a choice of whether to take the first or the last that's changed.  One could imagine taking the longest, but since Jose and Nupur tell me the overwritten words are at the end of the fragment, I figured I'd take the simpler route.

**Pull request merged**
