### PR TITLE
add frame number to metadata

### PR DESCRIPTION
**Pull request by ibsafa**
### Description

Put description of request here. Include _Fixes #XXX_ to link to an issue.

_If the full description is in a PR from a different repo, simply link that here, and delete the rest._

### Related Repository Branches

List related branches from other repos here (links to PRs even better!), if not linked above.

### Testing details
_(Note: edit as appropriate.)_
- *Where it was tested*: (e.g. SBN-FD, SBN-ND, DAB, etc.)
- *Run number associated with test*: 
- Other information:

### CODE REVIEW

**Comment by tomjunk** [comment]
How is the uncorrected frame number set or retrieved?

**Comment by tomjunk** [comment]
And a version number would be good.  Keep in mind, we have data with old NevisTPC fragments with old-style metadata.  How do we distinguish them?  You mention in Slack that you put in a line in the TPC Decoder that extracts the frame number:

fragment.metadata()->FrameNumber();

which works for data with a frame number, but points to other data in older data.  The _frame_number field looks like it takes the place in the order that _samples_per_channel used to have, and that reading old data with a new decoder will return the _samples_per_channel number as the frame number, unless we know from a version number not to do that.

**Comment by tomjunk** [comment]
And the new value got put in in the middle.  One thing about querying the size of the metadata -- artdaq fragments store data in 64 bit words.  Sometimes adding a smaller object will not change the size of the metadata because there were already some unused bits on the end, and thus using the metadata size as a cue for using the old metadata format vs the new one may not work.  Also, the new _frame_number field was not added to the end; it was put in the middle.

**Comment by tomjunk** [comment]
I suppose one could use the run number to ascertain the metadata version, as long as run numbers are monotonically increasing.

**Comment by ibsafa** [comment]
Hi @tomjunk the uncorrected frame number is no longer retrieved in the metadata, because we realized it is saved in the header which is available post decoding, and not needed here.

**Comment by ibsafa** [comment]
I agree we should have some way of identifying when the data structure changed. not sure what the best way to do that is. maybe we can have an error message in the decoder based on run number and sbndaq version, that says "Warning: you should be using vXX.YY.ZZ for runs <=K

**Review by afilkins — APPROVED** [review]

**Pull request merged**
