### PR TITLE
Feature/daphne

### PR DESCRIPTION
**Pull request by polabr**
### Description

Newest version of the DAPHNE Fragment class, as well as a unit test. 
Requires an input binary data file for testing (attached here: [data.bin.zip](https://github.com/SBNSoftware/sbndaq-artdaq-core/files/11004169/data.bin.zip))



### Testing details
- *Where it was tested*: (e.g. SBN-FD, SBN-ND, DAB, etc.): On sbnd-daq00 machine
- Other information: Instructions included at the top of unitTest.cc but I'll also post below

To use this unit test:                                                                                                                                                                                    
    Re-build workspace to compile this test.                                                                                                   
    Compiled binary will be outputted to this path:                                                                                                                                                       
        <your workspace>/build_slf7.x86_64/sbndaq_artdaq_core/slf7.x86_64.e20.s112.prof/bin/                                                                                                                                                                                                                                                                                                
    Make sure original binary data file ("data.bin") is in the above path.                                                                                                              
    Run the compiled unit test with ./unitTest                                                                                                                                                            
                                                                                                                                                                                                          
Output:                                                                                                                                                                                                   
    Script will output printout of data words in the structs to the terminal.                                                                                                                             
    This script also creates a file "output.txt" with original full binary data converted to hex for comparison. 

Note: Does not test looping structure of the structs in DAPHNEFragment class yet. This will be work for a future student.

### CODE REVIEW

**Review by wbadgett — APPROVED** [review]
looks good

**Comment by gennadiy-fnal** [comment]
The proposed code changes seem reasonable, but we need to verify the accuracy and validity of the resulting data.

**Review by gennadiy-fnal — CHANGES_REQUESTED** [review]
I have followed the instructions in the notes and reviewd the pull request. When running the unitTest program, it generated some output with values printed, but I noticed that the validity of these values was not being verified. In my opinion, this does not qualify as a proper test, but rather an example of a binary data dump. Additionally, it seems that the code in this pull request assigns values read from the bin file into the DAPHNEData structure and prints them out, which should actually be done by the DAPHNEFragment class by interpreting the binary data contained within the artdaq::Fragment class.

A better function test would involve the following steps:
1. Create an artdaq::Fragment and fill it with unmodified binary data.
2. Instantiate the DAPHNEFragment overlay class and use its operator<< operator to produce an output.
3. Compare the output with a valid reference output, which could be initially handmade.

Despite these issues, I view this as a good start in the right direction.

**Comment by wbadgett** [comment]
DAPHNE has been replaced, cancelling

**Pull request closed without merging**
