### PR TITLE
include active changes from Tereza Kroupova's version of sbnd_content.h

### PR DESCRIPTION
**Pull request by tomjunk**
This is a similar PR to this one

https://github.com/SBNSoftware/sbndaq-artdaq-core/pull/93

but the target branch is devleop instead of offline.  The changes to PTB_content.h are needed both by the online and offline.

### CODE REVIEW

**Comment by gennadiy-fnal** [comment]
@gvittis @tomjunk Please update the PR by adding the run number that was used to confirm that the proposed code was tested at SBND.

**Comment by tomjunk** [comment]
Very good.  I tested this along with the PTB decoder in https://github.com/SBNSoftware/sbndcode/pull/397 on Run 9660.
I enclose a few plots
run9660_llt_word_types
run9660_llt_triggerwords
run9660_llt_timestamps
run9660hltwordtypes
run9660hlttriggerwords
run9660hlttimestamps
run9660_chstatus_timestamps
run9660_chstatus_beam
run9660_chstatus_auxpds

**Comment by gennadiy-fnal** [comment]
I am merging this pull request into the release branch.

**Review by terezakroupa — COMMENTED** [review]
The changes here look good to me. I have some comments for the decoder itself, but I think this should just be updated. Thank you!

**Pull request merged**
